version: '3'
services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"        # HTTP
      - "--entryPoints.websecure.address=:443"  # HTTPS
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Permet à Traefik de détecter les conteneurs Docker
      - "./letsencrypt:/letsencrypt"  # Ce dossier peut être utilisé si vous décidez d'utiliser ACME plus tard (non utilisé pour l'instant)
      - "./certs:/certs"  # Lien vers le dossier où sont stockés vos certificats

  app:
    build: .
    container_name: app
    environment:
      NODE_ENV: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`https://ip172-18-0-102-cusnh0aim2rg00da5j60-3000.direct.labs.play-with-docker.com`)"  # Remplacez par votre domaine
      - "traefik.http.routers.app.entrypoints=websecure"  # Utilisation de HTTPS
      - "traefik.http.routers.app.tls=true"  # Activer TLS
      - "traefik.http.routers.app.tls.certificates[0].certFile=/certs/client.crt"  # Certificat SSL
      - "traefik.http.routers.app.tls.certificates[0].keyFile=/certs/client.key.pem"  # Clé privée SSL
    expose:
      - "3000"   # Expose le port interne 3000 de votre app (accessible seulement par Traefik)
    networks:
      - web

networks:
  web:
    external: true  # Utiliser un réseau externe pour que Traefik et l'app puissent se connecter
